/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package coreCSMS.UI;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.ImageIcon;
import javax.swing.table.DefaultTableModel;
import javax.swing.*;

/**
 *
 * @author hp-pc
 */
public class ViewPeople extends javax.swing.JInternalFrame {

    public NewMDIApplication mdiObj = null;
    
    /**
     * Creates new form ViewPeople
     */
    public ViewPeople(NewMDIApplication mdiObj) {
        this.mdiObj = mdiObj;
        
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator1 = new javax.swing.JSeparator();
        imagePanelLogo = new coreCSMS.UI.ImagePanel();
        jLabel2 = new javax.swing.JLabel();
        jTabbedPanePeople = new javax.swing.JTabbedPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableAdmins = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableCustomers = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTableSuppliers = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtSearchKey = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("View People");
        addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                formFocusGained(evt);
            }
        });

        jPanel2.setBackground(java.awt.SystemColor.controlShadow);
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, null, java.awt.SystemColor.activeCaptionText));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Icons/New Icons/IconsPNG/ViewPeople.png"))); // NOI18N

        jSeparator2.setBackground(java.awt.SystemColor.desktop);
        jSeparator2.setForeground(java.awt.SystemColor.controlLtHighlight);
        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        javax.swing.GroupLayout imagePanelLogoLayout = new javax.swing.GroupLayout(imagePanelLogo);
        imagePanelLogo.setLayout(imagePanelLogoLayout);
        imagePanelLogoLayout.setHorizontalGroup(
            imagePanelLogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 108, Short.MAX_VALUE)
        );
        imagePanelLogoLayout.setVerticalGroup(
            imagePanelLogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 64, Short.MAX_VALUE)
        );

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setText("VIEW PEOPLE");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 943, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 8, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(imagePanelLogo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jSeparator2)
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(imagePanelLogo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTableAdmins.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "USERNAME"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTableAdmins);

        jTabbedPanePeople.addTab("Administrators", jScrollPane1);

        jTableCustomers.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "CUSTOMER ID", "CUSTOMER NAME", "CUSTOMER PH NO"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTableCustomers);

        jTabbedPanePeople.addTab("Customers", jScrollPane2);

        jTableSuppliers.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "SUPPLIER ID", "SUPPLIER NAME", "SUPPLIER ADDRESS", "SUPPLIER PH NO"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(jTableSuppliers);

        jTabbedPanePeople.addTab("Suppliers", jScrollPane3);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Icons/New Icons/IconsPNG/1457686460_arrow-refresh.png"))); // NOI18N
        jButton2.setText("Refresh");
        jButton2.setToolTipText("Refresh");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Icons/New Icons/IconsPNG/1456622100_eye.png"))); // NOI18N
        jButton1.setText("View Person...");
        jButton1.setToolTipText("View Person...");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel3.setText("Search Administrator Username/Customer Name/Supplier Name:");

        txtSearchKey.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        txtSearchKey.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtSearchKeyFocusGained(evt);
            }
        });

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Icons/New Icons/IconsPNG/1458091263_xmag.png"))); // NOI18N
        jButton3.setText("Search");
        jButton3.setToolTipText("Search");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTabbedPanePeople)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(68, 68, 68)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(txtSearchKey, javax.swing.GroupLayout.PREFERRED_SIZE, 442, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTabbedPanePeople, javax.swing.GroupLayout.DEFAULT_SIZE, 401, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtSearchKey, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton2)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton3)
                        .addComponent(jButton1)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    public void searchPerson()  {
        refreshViewAllTable(jTabbedPanePeople.getSelectedIndex());
        
        switch(jTabbedPanePeople.getSelectedIndex())    {
            case 0:
                if(txtSearchKey.getText().length()!=0)   {
                    try {
                        Class.forName("sun.jdbc.odbc.JdbcOdbcDriver");
                        Connection con = DriverManager.getConnection("jdbc:odbc:MyDSN_256");
                    
                        Statement st = con.createStatement();
                        ResultSet rs = st.executeQuery("Select username from Admins where username LIKE '%" + txtSearchKey.getText() + "%'");
                        ResultSetMetaData rsMeta = rs.getMetaData();
                        rs.setFetchDirection(ResultSet.FETCH_FORWARD);
                        int columnCount = rsMeta.getColumnCount();
                        DefaultTableModel tableModel = (DefaultTableModel) jTableAdmins.getModel();
                    
                        tableModel.setRowCount(0);
                        if(!rs.next())  {
                            JOptionPane.showMessageDialog(rootPane, "Administrator Not Found!", "CSMS - Error" , JOptionPane.ERROR_MESSAGE);
                            refreshViewAllTable(0);
                            rs.close();
                        }
                        else    {
                            rs = st.executeQuery("Select username from Admins where username LIKE '%" + txtSearchKey.getText() + "%'");
                            rsMeta = rs.getMetaData();
                            rs.setFetchDirection(ResultSet.FETCH_FORWARD);
                            columnCount = rsMeta.getColumnCount();
                            tableModel = (DefaultTableModel) jTableAdmins.getModel();
                    
                            tableModel.setRowCount(0);
                            while(rs.next())    {
                                String[] conList = new String[columnCount];
                                for(int i = 1, j = 0; i <= columnCount; i++, j++)   {
                                    conList[j] = rs.getString(i);
                                }
                                tableModel.addRow(conList);
                            }
                            rs.close();
                        }
                        
                        st.close();
                        con.close();                    
                    }
                    catch(ClassNotFoundException cnfe) {}
                    catch(SQLException sqle)    {}
                }
                else
                    JOptionPane.showMessageDialog(rootPane, "Please Enter Complete and Valid Values!", "CSMS - Error" , JOptionPane.ERROR_MESSAGE);
                break;
                
            case 1:
                if(txtSearchKey.getText().length()!=0)   {
                try {
                    Class.forName("sun.jdbc.odbc.JdbcOdbcDriver");
                    Connection con = DriverManager.getConnection("jdbc:odbc:MyDSN_256");
                    
                    Statement st = con.createStatement();
                    ResultSet rs = st.executeQuery("Select cust_id, cust_name, cust_phno from Customers where cust_name LIKE '%" + txtSearchKey.getText() + "%' order by cust_id");
                    ResultSetMetaData rsMeta = rs.getMetaData();
                    rs.setFetchDirection(ResultSet.FETCH_FORWARD);
                    int columnCount = rsMeta.getColumnCount();
                    DefaultTableModel tableModel = (DefaultTableModel) jTableCustomers.getModel();
                    
                    tableModel.setRowCount(0);
                    if(!rs.next())  {
                        JOptionPane.showMessageDialog(rootPane, "Customer Not Found!", "CSMS - Error" , JOptionPane.ERROR_MESSAGE);
                        refreshViewAllTable(1);
                            rs.close();
                    }
                    else    {
                        rs = st.executeQuery("Select cust_id, cust_name, cust_phno from Customers where cust_name LIKE '%" + txtSearchKey.getText() + "%' order by cust_id");
                        rsMeta = rs.getMetaData();
                        rs.setFetchDirection(ResultSet.FETCH_FORWARD);
                        columnCount = rsMeta.getColumnCount();
                        tableModel = (DefaultTableModel) jTableCustomers.getModel();
                    
                        tableModel.setRowCount(0);
                        while(rs.next())    {
                            String[] conList = new String[columnCount];
                            for(int i = 1, j = 0; i <= columnCount; i++, j++)   {
                                conList[j] = rs.getString(i);
                            }
                            tableModel.addRow(conList);
                        }
                        rs.close();
                    }
                     
                    st.close();
                    con.close();
                    
                }
                catch(ClassNotFoundException cnfe) {}
                catch(SQLException sqle)    {}
                }
                else
                    JOptionPane.showMessageDialog(rootPane, "Please Enter Complete and Valid Values!", "CSMS - Error" , JOptionPane.ERROR_MESSAGE);
                break;
                
            case 2:
                if(txtSearchKey.getText().length()!=0)   {
                try {
                    Class.forName("sun.jdbc.odbc.JdbcOdbcDriver");
                    Connection con = DriverManager.getConnection("jdbc:odbc:MyDSN_256");
                    
                    Statement st = con.createStatement();
                    ResultSet rs = st.executeQuery("Select supplier_id, supplier_name, supplier_address from Suppliers where supplier_name LIKE '%" + txtSearchKey.getText() + "%' order by supplier_id");
                    ResultSetMetaData rsMeta = rs.getMetaData();
                    rs.setFetchDirection(ResultSet.FETCH_FORWARD);
                    int columnCount = rsMeta.getColumnCount();
                    DefaultTableModel tableModel = (DefaultTableModel) jTableSuppliers.getModel();
                    
                    tableModel.setRowCount(0);
                    if(!rs.next())  {
                        JOptionPane.showMessageDialog(rootPane, "Supplier Not Found!", "CSMS - Error" , JOptionPane.ERROR_MESSAGE);
                        refreshViewAllTable(1);
                            rs.close();
                    }
                    else    {
                        rs = st.executeQuery("Select supplier_id, supplier_name, supplier_address from Suppliers where supplier_name LIKE '%" + txtSearchKey.getText() + "%' order by supplier_id");
                        rsMeta = rs.getMetaData();
                        rs.setFetchDirection(ResultSet.FETCH_FORWARD);
                        columnCount = rsMeta.getColumnCount();
                        tableModel = (DefaultTableModel) jTableSuppliers.getModel();
                    
                        tableModel.setRowCount(0);
                        while(rs.next())    {
                            String[] conList = new String[columnCount];
                            for(int i = 1, j = 0; i <= columnCount; i++, j++)   {
                                conList[j] = rs.getString(i);
                            }
                            tableModel.addRow(conList);
                        }
                        rs.close();
                    }
                     
                    st.close();
                    con.close();
                    
                }
                catch(ClassNotFoundException cnfe) {}
                catch(SQLException sqle)    {}
                }
                else
                    JOptionPane.showMessageDialog(rootPane, "Please Enter Complete and Valid Values!", "CSMS - Error" , JOptionPane.ERROR_MESSAGE);
                break;
        }
    }
    
    public void refreshViewAllTable(int tabIndex)   {
        jTabbedPanePeople.setSelectedIndex(tabIndex);
        
        for(int x=0; x<3; x++)  {
        
        switch(x)    {
            case 0:
                try {
                    Class.forName("sun.jdbc.odbc.JdbcOdbcDriver");
                    Connection con = DriverManager.getConnection("jdbc:odbc:MyDSN_256");
                    
                    Statement st = con.createStatement();
                    ResultSet rs = st.executeQuery("Select username from Admins");
                    ResultSetMetaData rsMeta = rs.getMetaData();
                    rs.setFetchDirection(ResultSet.FETCH_FORWARD);
                    int columnCount = rsMeta.getColumnCount();
                    DefaultTableModel tableModel = (DefaultTableModel) jTableAdmins.getModel();
                    
                    tableModel.setRowCount(0);
                    while(rs.next())    {
                        String[] conList = new String[columnCount];
                        for(int i = 1, j = 0; i <= columnCount; i++, j++)   {
                            conList[j] = rs.getString(i);
                        }
                        tableModel.addRow(conList);
                    }
                    rs.close();
                    st.close();
                    con.close();
                    
                }
                catch(ClassNotFoundException cnfe) {}
                catch(SQLException sqle)    {}
                
                break;
            case 1:
                try {
                    Class.forName("sun.jdbc.odbc.JdbcOdbcDriver");
                    Connection con = DriverManager.getConnection("jdbc:odbc:MyDSN_256");
                    
                    Statement st = con.createStatement();
                    ResultSet rs = st.executeQuery("Select * from Customers order by cust_id");
                    ResultSetMetaData rsMeta = rs.getMetaData();
                    rs.setFetchDirection(ResultSet.FETCH_FORWARD);
                    int columnCount = rsMeta.getColumnCount();
                    DefaultTableModel tableModel = (DefaultTableModel) jTableCustomers.getModel();
                    
                    tableModel.setRowCount(0);
                    while(rs.next())    {
                        String[] conList = new String[columnCount];
                        for(int i = 1, j = 0; i <= columnCount; i++, j++)   {
                            conList[j] = rs.getString(i);
                        }
                        tableModel.addRow(conList);
                    }
                    rs.close();
                    st.close();
                    con.close();
                    
                }
                catch(ClassNotFoundException cnfe) {}
                catch(SQLException sqle)    {}
                
                break;
            case 2:
                try {
                    Class.forName("sun.jdbc.odbc.JdbcOdbcDriver");
                    Connection con = DriverManager.getConnection("jdbc:odbc:MyDSN_256");
                    
                    Statement st = con.createStatement();
                    ResultSet rs = st.executeQuery("Select * from Suppliers order by supplier_id");
                    ResultSetMetaData rsMeta = rs.getMetaData();
                    rs.setFetchDirection(ResultSet.FETCH_FORWARD);
                    int columnCount = rsMeta.getColumnCount();
                    DefaultTableModel tableModel = (DefaultTableModel) jTableSuppliers.getModel();
                    
                    tableModel.setRowCount(0);
                    while(rs.next())    {
                        String[] conList = new String[columnCount];
                        for(int i = 1, j = 0; i <= columnCount; i++, j++)   {
                            conList[j] = rs.getString(i);
                        }
                        tableModel.addRow(conList);
                    }
                    rs.close();
                    st.close();
                    con.close();
                    
                }
                catch(ClassNotFoundException cnfe) {}
                catch(SQLException sqle)    {}
                
                break;
        }
        }
    }
    
    public void requestFocusOfTxtSearchKey()    {
        txtSearchKey.requestFocus();
    }

    
    private void formFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_formFocusGained
        // TODO add your handling code here:
        imagePanelLogo.setImage(new ImageIcon(this.getClass().getResource("\\..\\..\\Images\\Logos\\CSMS\\CSMS2 final logo Small.jpg")).getImage());
        repaint();
        
        try {
            this.setMaximum(true);
        }
        catch(java.beans.PropertyVetoException e)  {}
    }//GEN-LAST:event_formFocusGained

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        txtSearchKey.setText("");
        refreshViewAllTable(jTabbedPanePeople.getSelectedIndex());
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int selectedRowIndex;
        txtSearchKey.setText("");

        switch(jTabbedPanePeople.getSelectedIndex())  {
            case 0:
            selectedRowIndex = jTableAdmins.getSelectedRow();
            if(selectedRowIndex != -1)  {
                mdiObj.addAdministratorObj.selectOperationsTab2((jTableAdmins.getModel().getValueAt(selectedRowIndex, 0)).toString());
                mdiObj.addAdministratorObj.setVisible(false);
                mdiObj.addAdministratorObj.setVisible(true);
                mdiObj.addAdministratorObj.requestFocus();
                this.setVisible(false);
            }
            else    {
                JOptionPane.showMessageDialog(rootPane, "Please Select a Person first!", "CSMS - Error" , JOptionPane.ERROR_MESSAGE);
            }
            break;

            case 1:
            selectedRowIndex = jTableCustomers.getSelectedRow();
            if(selectedRowIndex != -1)  {
                mdiObj.addCustomerObj.selectOperationsTab2(Integer.parseInt((jTableCustomers.getModel().getValueAt(selectedRowIndex, 0)).toString()));
                mdiObj.addCustomerObj.setVisible(false);
                mdiObj.addCustomerObj.setVisible(true);
                mdiObj.addCustomerObj.requestFocus();
                this.setVisible(false);
            }
            else    {
                JOptionPane.showMessageDialog(rootPane, "Please Select a Person first!", "CSMS - Error" , JOptionPane.ERROR_MESSAGE);
            }
            break;

            case 2:
            selectedRowIndex = jTableSuppliers.getSelectedRow();
            if(selectedRowIndex != -1)  {
                mdiObj.addSupplierObj.selectOperationsTab2(Integer.parseInt((jTableSuppliers.getModel().getValueAt(selectedRowIndex, 0)).toString()));
                mdiObj.addSupplierObj.setVisible(false);
                mdiObj.addSupplierObj.setVisible(true);
                mdiObj.addSupplierObj.requestFocus();
                this.setVisible(false);
            }
            else    {
                JOptionPane.showMessageDialog(rootPane, "Please Select a Person first!", "CSMS - Error" , JOptionPane.ERROR_MESSAGE);
            }
            break;
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtSearchKeyFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtSearchKeyFocusGained
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtSearchKeyFocusGained

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        searchPerson();
    }//GEN-LAST:event_jButton3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private coreCSMS.UI.ImagePanel imagePanelLogo;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTabbedPane jTabbedPanePeople;
    private javax.swing.JTable jTableAdmins;
    private javax.swing.JTable jTableCustomers;
    private javax.swing.JTable jTableSuppliers;
    private javax.swing.JTextField txtSearchKey;
    // End of variables declaration//GEN-END:variables
}
